# Generated by Django 5.2 on 2026-01-10 04:52

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.CharField(default=core.models.generate_enrollment_no, editable=False, max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('father_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('course_code', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('session', models.CharField(blank=True, max_length=50, null=True)),
                ('roll_no', models.CharField(blank=True, max_length=50, null=True)),
                ('tenth_marksheet', models.ImageField(blank=True, null=True, upload_to='students/10th/')),
                ('twelfth_marksheet', models.ImageField(blank=True, null=True, upload_to='students/12th/')),
                ('aadhaar_card', models.ImageField(blank=True, null=True, upload_to='students/aadhaar/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photo/')),
                ('center_name', models.CharField(blank=True, max_length=255, null=True)),
                ('center_code', models.CharField(blank=True, max_length=50, null=True)),
                ('center_address', models.TextField(blank=True, null=True)),
                ('admission_receipt', models.FileField(blank=True, null=True, upload_to='admission_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course')),
            ],
        ),
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.JSONField(default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='marksheets/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marksheets', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical')], max_length=10)),
                ('year', models.CharField(choices=[('first', 'First Year'), ('second', 'Second Year')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
            ],
        ),
    ]
