# Generated by Django 5.2 on 2026-01-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marksheet',
            name='created_at',
        ),
        migrations.AddField(
            model_name='marksheet',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='marksheets/'),
        ),
    ]
