# Generated by Django 5.2 on 2026-01-10 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='year',
            field=models.CharField(choices=[('first', 'First Year'), ('second', 'Second Year')], default='first', max_length=10),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='marks',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
    ]
