# Generated by Django 5.2 on 2026-01-07 05:43

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(default=core.models.generate_registration_id, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('father_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('tenth_marksheet', models.ImageField(upload_to='students/10th/')),
                ('twelfth_marksheet', models.ImageField(upload_to='students/12th/')),
                ('photo', models.ImageField(upload_to='students/photo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
