# Generated by Django 5.2 on 2026-01-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_marksheet_created_at_marksheet_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_receipt',
            field=models.FileField(blank=True, null=True, upload_to='admission_receipts/'),
        ),
    ]
