# Generated by Django 5.2 on 2026-01-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_admission_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='center_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='center_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='center_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
