# Generated by Django 5.2 on 2026-01-07 06:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadhaar_card',
            field=models.ImageField(blank=True, null=True, upload_to='students/aadhaar/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photo/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_id',
            field=models.CharField(default=core.models.generate_registration_id, editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='tenth_marksheet',
            field=models.ImageField(blank=True, null=True, upload_to='students/10th/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='twelfth_marksheet',
            field=models.ImageField(blank=True, null=True, upload_to='students/12th/'),
        ),
    ]
