# Generated by Django 5.2 on 2026-01-09 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.center'),
        ),
    ]
