# Generated by Django 5.2 on 2026-01-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_student_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='center',
        ),
        migrations.AddField(
            model_name='center',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
